apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett
  namespace: default
  labels:
    app: jackett
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jackett
  template:
    metadata:
      labels:
        app: jackett
    spec:
      containers:
        - image: lscr.io/linuxserver/jackett:latest
          imagePullPolicy: Always
          name: jackett
          resources: {}
          env:
            - name: PGID
              value: "65534"
            - name: PUID
              value: "65534"
            - name: TZ
              value: "Iceland"
            - name: AUTO_UPDATE
              value: "false"
            - name: RUN_OPTS
              value: "-n true --NoRestart"
          ports:
            - name: jackett
              containerPort: 9117
          livenessProbe:
            httpGet:
              path: /health
              port: jackett
            initialDelaySeconds: 150
            periodSeconds: 30
            timeoutSeconds: 30
          volumeMounts:
            - name: host-disk1
              mountPath: /config
              subPath: jackett
      volumes:
        - name: host-disk1
          hostPath:
            path: /disk1
      restartPolicy: Always
status: {}
