apiVersion: apps/v1
kind: Deployment
metadata:
  name: sickchill
  namespace: default
  labels:
    app: sickchill
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sickchill
  template:
    metadata:
      labels:
        app: sickchill
    spec:
      containers:
        - image: linuxserver/sickchill:latest
          imagePullPolicy: Always
          name: sickchill
          resources: {}
          env:
            - name: PGID
              value: "65534"
            - name: PUID
              value: "65534"
          ports:
            - name: sickchill
              containerPort: 8081
          livenessProbe:
            httpGet:
              path: /
              port: sickchill
            initialDelaySeconds: 60
            periodSeconds: 20
          volumeMounts:
            - name: host-disk1
              mountPath: /config
              subPath: sickchill
            - name: nfs-vol-disk2
              mountPath: /disk2
            - name: nfs-vol-disk3
              mountPath: /disk3
      volumes:
        - name: host-disk1
          hostPath:
            path: /disk1
        - name: nfs-vol-disk2
          nfs:
            server: 192.168.1.2
            path: /disk2
        - name: nfs-vol-disk3
          nfs:
            server: 192.168.1.2
            path: /disk3
      restartPolicy: Always
status: {}
