---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubenav
  labels:
    app.kubernetes.io/instance: kubenav
    app.kubernetes.io/name: kubenav
subjects:
  - kind: ServiceAccount
    name: kubenav
    namespace: kubenav
roleRef:
  kind: ClusterRole
  name: kubenav
  apiGroup: rbac.authorization.k8s.io
