apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: transmission
  labels:
    app: transmission
spec:
  selector:
    matchLabels:
      app: transmission
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: transmission
    spec:
      containers:
        - env:
            - name: PUID
              value: "65534"
            - name: PGID
              value: "65534"
            - name: TZ
              value: Atlantic/Reykjavik
          image: linuxserver/transmission
          name: transmission
          livenessProbe:
            tcpSocket:
              port: 9091
            initialDelaySeconds: 120
            periodSeconds: 15
            timeoutSeconds: 30
          ports:
            - name: http
              containerPort: 9091
              protocol: TCP
            - containerPort: 51413
              protocol: TCP
            - containerPort: 51413
              protocol: UDP
          resources: {}
          volumeMounts:
            - name: hostpath-vol-disk3
              mountPath: /disk3
            - name: hostpath-vol-disk1-config
              mountPath: /config
            - name: hostpath-vol-disk1-watch
              mountPath: /watch
      restartPolicy: Always
      volumes:
        - name: hostpath-vol-disk1-config
          hostPath:
            path: /disk1/transmission-config
            type: DirectoryOrCreate
        - name: hostpath-vol-disk1-watch
          hostPath:
            path: /disk1/transmission-watch
            type: DirectoryOrCreate
        - name: hostpath-vol-disk3
          hostPath:
            path: /disk3
            type: DirectoryOrCreate

status: {}
