apiVersion: v1
kind: Service
metadata:
  name: transmission
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 9091
      targetPort: 9091
      protocol: TCP
      name: http
      nodePort: 30001 
    - port: 51413
      targetPort: 51413
      protocol: TCP
      name: tcp5
      nodePort: 30002     
    - port: 51413
      targetPort: 51413
      protocol: UDP
      name: udp5
      nodePort: 30002
  selector:
    app.kubernetes.io/name: portainer
    app.kubernetes.io/instance: portainer