kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pvc
  namespace: default  
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage    
  resources:
    requests:
      storage: 10Gi