kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: portainer-pvc
  namespace: portainer  
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage    
  resources:
    requests:
      storage: 10Gi