apiVersion: apps/v1
kind: Deployment
metadata:
  name: calibre
  namespace: default
  labels:
    app: calibre
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calibre
  template:
    metadata:
      labels:
        app: calibre
    spec:
      containers:
      - image: linuxserver/calibre:latest
        imagePullPolicy: Always
        name: calibre
        resources: {}
        env: 
        - name: PGID
          value: "65534"
        - name: PUID
          value: "65534"
        - name: TZ
          value: Atlantic/Reykjavik
        ports:
        - name: calibre-8080
          containerPort: 8080
          hostPort: 8080
        - name: calibre-8081
          containerPort: 8081
          hostPort: 8081
        livenessProbe:
          httpGet:
            path: /
            port: calibre
          initialDelaySeconds: 60
          periodSeconds: 20
        volumeMounts:
        - name: host-disk1
          mountPath: /config
          subPath: calibre 
        - mountPath: /books
          name: nfs-vol-disk3
          subPath: books
      volumes:
        - name: host-disk1
          hostPath:
            path: /disk1
        - name: nfs-vol-disk3
          nfs:
            server: 192.168.1.2
            path: /disk3
      restartPolicy: Always
status: {}