kind: Service
apiVersion: v1
metadata:
  name: pihole-tcp
  namespace: default
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole # < annotation name to combine the Service IP, make sure it's same name as in the service UDP yaml
spec:
  selector:
    app: pihole
  ports:
    - name: pihole-http
      port: 80
      protocol: TCP
      targetPort: pihole-http
    - name: pihole-https
      port: 443
      protocol: TCP
      targetPort: pihole-https
    - name: dns
      port: 53
      protocol: TCP
      targetPort: dns
  type: LoadBalancer
  loadBalancerIP: 192.168.1.82
