kind: Service
apiVersion: v1
metadata:
  name: pihole-udp
  namespace: default
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole # < annotation name to combine the Service IP, make sure it's same name as in the service UDP yaml
spec:
  selector:
    app: pihole
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: dns-udp
    - name: client-udp
      port: 67
      protocol: UDP
      targetPort: client-udp
  externalTrafficPolicy: Local
  type: LoadBalancer
  loadBalancerIP: 192.168.1.82
